#!/usr/bin/python3

def check_factors(number_list):
    """Check the factors of numbers in a list"""
    import sys

    if len(number_list) == 0 or number_list is None:
        print("An error occurred")
    for number in number_list:
        num = int(number)
        for divisor in range(2, sys.maxsize):
            if num % divisor == 0:
                quotient = int(num / divisor)
                print("{:d} = {:d} * {:d}".format(num, quotient, divisor))
                break

def factoring_challenge():
    """Factorize numbers from a file"""
    import sys

    args = sys.argv
    if len(args) < 2:
        print("Error! Usage: ./factors filename")
        exit(98)
    file_name = args[1]
    with open(file_name) as file_in:
        lines = file_in.readlines()
    check_factors(lines)

factoring_challenge()
